// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YadSara.Data;

#nullable disable

namespace YadSara.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("YadSara.Core.Entities.Borrow", b =>
                {
                    b.Property<string>("borrowId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("borrowName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("cityId")
                        .HasColumnType("int");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("borrowId");

                    b.ToTable("Borrow");
                });

            modelBuilder.Entity("YadSara.Core.Entities.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"), 1L, 1);

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CityId");

                    b.ToTable("City");
                });

            modelBuilder.Entity("YadSara.Core.Entities.Equipment", b =>
                {
                    b.Property<int>("idEquipment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idEquipment"), 1L, 1);

                    b.Property<int>("currentquantity")
                        .HasColumnType("int");

                    b.Property<string>("deposit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lenderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nameEquipment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("nameEquipmentck")
                        .HasColumnType("int");

                    b.HasKey("idEquipment");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("YadSara.Core.Entities.Lender", b =>
                {
                    b.Property<string>("lenderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("lenderAdress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("lenderCityId")
                        .HasColumnType("int");

                    b.Property<string>("lenderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lenderPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("lenderId");

                    b.ToTable("Lender");
                });

            modelBuilder.Entity("YadSara.Core.Entities.Lending", b =>
                {
                    b.Property<int>("LendingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LendingId"), 1L, 1);

                    b.Property<int>("IdEquipment")
                        .HasColumnType("int");

                    b.Property<bool>("IsReturned")
                        .HasColumnType("bit");

                    b.Property<DateTime>("TimeLending")
                        .HasColumnType("datetime2");

                    b.Property<string>("borrowId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("deadlineLending")
                        .HasColumnType("datetime2");

                    b.Property<string>("lenderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LendingId");

                    b.ToTable("Lending");
                });
#pragma warning restore 612, 618
        }
    }
}
